namespace Cml.Lexing;

public enum Symbols
{
    Unknown,
    CurlyOpen,
    CurlyClose,
    CircleOpen,
    CircleClose,
    SquareOpen,
    SquareClose,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Ampersand,
    AmpersandAmpersand,
    Verticalbar,
    VerticalbarVerticalbar,
    UpArrow,
    Tilda,
    LeftShift,
    RightShift,
    IsEquals,
    NotEquals,
    LessEquals,
    GreaterEquals,
    Less,
    Greater,
    Equals,
    PlusEquals,
    MinusEquals,
    MultiplyEquals,
    DivideEquals,
    ReminderEquals,
    LeftShiftEquals,
    RightShiftEquals,
    AndEquals,
    OrEquals,
    XorEquals,
    ExclamationMark,
    Increment,
    Decrement,
    NegateEquals,
    Semicolon,
    Dot,
}

// +, -, *, /, %, &, &&, |, ||, ^, ~, !, <<, >>, ==, !=, <=, >=, <, >, =, +=, -=, *=, /=, %=, <<=, >>=, &=, |=, ^=, --, ++, .